id = hr_y_app
name = HR-Y App
mainURL = https://hr-y.com/app/
icon = icon.png
allowSubdomains = true
requireDoubleBackToExit = true
enableExternalLinks = true
openExternalLinksInBrowser = true
confirmOpenInBrowser = true
allowOpenMobileApp = false
JSEnabled = true
DomStorageEnabled = true
